import React,{useState} from 'react'
import {View,Text,ScrollView,TouchableOpacity} from 'react-native'
import {Card,Button,Badge,styles} from './CareUI'

export const taskFields=team=>[['title','What needs to happen?'],['details','Handover details','textarea'],['assigned_to','Responsible colleague','select',[{value:'',label:'Choose colleague'},...team.map(m=>({value:m.id,label:m.name+' · '+m.role}))]],['due_at','Due date and time','datetime'],['priority','Priority','select',['routine','urgent']]]
function group(task){if(['completed','cancelled'].includes(task.status))return 'closed';if(task.priority==='urgent'||new Date(task.due_at)<new Date())return 'urgent';if(task.status==='waiting')return 'waiting';return new Date(task.due_at).toDateString()===new Date().toDateString()?'today':'upcoming'}
export default function CareTasks({rows,team,user,open,onLaboratory,onHistoryChange}){
 const [selected,setSelected]=useState('urgent'),[mine,setMine]=useState(true)
 const groups=[['urgent','Urgent & overdue'],['today','Today'],['upcoming','Upcoming'],['waiting','Waiting'],['closed','Closed']]
 const visible=rows.filter(t=>(!mine||t.assigned_to===user.id||!t.assigned_to)&&group(t)===selected)
 return <View style={{gap:16}}><Button onPress={()=>open('Assign a task','task_create',taskFields(team),{assigned_to:user.id,priority:'routine'})}>Assign a task</Button><Button ghost onPress={()=>setMine(!mine)}>{mine?'Showing my tasks · show all accessible':'Showing all accessible · show mine'}</Button><ScrollView horizontal showsHorizontalScrollIndicator={false}>{groups.map(([key,label])=><TouchableOpacity accessibilityRole="button" accessibilityState={{selected:selected===key}} key={key} onPress={()=>{setSelected(key);onHistoryChange(key==='closed')}} style={[styles.tab,selected===key&&styles.activeTab]}><Text style={[styles.tabText,selected===key&&styles.activeText]}>{label}</Text></TouchableOpacity>)}</ScrollView>
 {visible.map(t=><Card key={t.id} title={t.title}><Badge value={t.priority==='urgent'?'urgent':t.status}/><Text style={styles.muted}>{t.patient_id||'Institution task'}</Text><Text style={styles.subtitle}>{t.details}</Text><Text style={styles.subtitle}>Due {new Date(t.due_at).toLocaleString()}</Text><Text style={styles.subtitle}>Owner: {team.find(m=>m.id===t.assigned_to)?.name||'Owner needs review'}</Text>{t.outcome&&<Text style={styles.subtitle}>{t.outcome}</Text>}{t.source==='lab_review'&&group(t)!=='closed'&&<Button onPress={onLaboratory}>Open laboratory</Button>}{group(t)!=='closed'&&<Button ghost onPress={()=>open('Update or hand over task','task_update',[['status','Task status','select',t.source==='lab_review'?['open','in_progress','waiting']:['open','in_progress','waiting','completed','cancelled']],['assigned_to','Responsible colleague','select',team.filter(m=>t.source!=='lab_review'||['admin','doctor'].includes(m.role)).map(m=>({value:m.id,label:m.name+' · '+m.role}))],['outcome','Outcome or reason for waiting','textarea']],{id:t.id,version:t.version,status:t.status,assigned_to:t.assigned_to||user.id})}>Update task</Button>}</Card>)}
 {!visible.length&&<Text style={styles.muted}>No tasks in this view.</Text>}
 </View>
}
