import React from 'react'
import {View,Text,TouchableOpacity,StyleSheet} from 'react-native'
import {Card,Button,Badge,styles} from './CareUI'
import {dashboardRoles,dashboardWork} from '../lib/dashboard.mjs'

export default function NativeDashboard({role,data,facility,user,onAction,onPatient,loading,lastUpdated,error}) {
  const config=dashboardRoles[role]||dashboardRoles.patient, work=dashboardWork(role,data,facility,user.id)
  const stats=role==='doctor'?[['Patients waiting',work.visits.length,'patients'],['Results to review',work.labs.length,'lab']]:role==='nurse'?[['Open visits',work.visits.length,'patients'],['Upcoming bookings',work.appointments.length,'appointments']]:role==='labtech'?[['Tests to process',work.labs.length,'lab'],['My tasks',work.tasks.length,'tasks']]:role==='pharmacist'?[['Current prescriptions',work.prescriptions.length,'pharmacy'],['Batches needing attention',work.stock.length,'stock']]:role==='admin'?[['Active staff',work.members.length,'team'],['Patient link requests',work.links.length,'team']]:[['Current medicines',work.prescriptions.length,'medicines'],['Upcoming appointments',work.appointments.length,'appointments']]
  return <View style={{gap:18}}>
    <View style={local.hero}><Text style={local.eyebrow}>{config.eyebrow}</Text><Text style={styles.title}>{config.title}</Text><Text style={styles.subtitle}>{config.description}</Text><Button onPress={()=>onAction(config.actions[0][0])}>{config.actions[0][1]}</Button></View>
    <View style={local.actions}>{config.actions.slice(1).map(([key,label])=><TouchableOpacity key={key} accessibilityRole="button" onPress={()=>onAction(key)} style={local.action}><Text style={local.actionText}>{label} →</Text></TouchableOpacity>)}</View>
    <Text accessibilityLiveRegion="polite" style={styles.muted}>{loading?'Updating your worklist…':error?'Could not refresh. Showing the last loaded worklist.':lastUpdated?'Updated '+lastUpdated.toLocaleTimeString()+'. Pull down to refresh.':'Pull down to load your worklist.'}</Text>
    <View style={local.actions}>{stats.map(([label,value,target])=><TouchableOpacity key={label} accessibilityRole="button" accessibilityLabel={label+': '+(lastUpdated?value:'not loaded')} onPress={()=>onAction(target)} style={local.stat}><Text style={local.count}>{lastUpdated?value:'—'}</Text><Text style={styles.subtitle}>{label}</Text></TouchableOpacity>)}</View>
    <Text style={styles.muted}>Counts reflect the loaded worklists, up to 100 records each.</Text>
    {role==='patient'?<>
      <Card title="Your next appointment">{work.appointments[0]?<><Text style={styles.heading}>{new Date(work.appointments[0].scheduled_at).toLocaleString()}</Text><Badge value={work.appointments[0].status}/><Text style={styles.subtitle}>{work.appointments[0].reason}</Text></>:<Text style={styles.muted}>{lastUpdated?'No upcoming appointment recorded.':'Appointments have not loaded yet.'}</Text>}<Button ghost onPress={()=>onAction('appointments')}>View appointments</Button></Card>
      <Card title="Your health information">{[['medicines','My medicines'],['history','Results & visit history'],['payments','My receipts']].map(([key,label])=><Button key={key} ghost onPress={()=>onAction(key)}>{label}</Button>)}</Card>
    </>:<>
      {work.tasks.length>0&&<Card title="Your next actions">{work.tasks.slice(0,3).map(t=><View key={t.id} style={local.item}><Text style={styles.heading}>{t.title}</Text><Text style={styles.muted}>Due {new Date(t.due_at).toLocaleString()}</Text>{t.priority==='urgent'&&<Badge value="urgent"/>}</View>)}<Button ghost onPress={()=>onAction('tasks')}>All my tasks</Button></Card>}
      {['doctor','nurse'].includes(role)&&<Card title={role==='nurse'?'Arrivals needing care':'Consultation queue'}>{work.visits.slice(0,4).map(v=>{const p=(data.patientNames||[]).find(p=>p.id===v.patient_id);return <View key={v.id} style={local.item}><Text style={styles.heading}>{p?[p.first_name,p.last_name].join(' '):v.patient_id}</Text><View style={{flexDirection:'row',gap:8,flexWrap:'wrap'}}><Badge value={v.status}/><Badge value={v.priority}/></View><Button ghost onPress={()=>onPatient(v.patient_id)}>Open patient</Button></View>})}{!work.visits.length&&<Text style={styles.muted}>{lastUpdated?'No open visits in the loaded worklist.':'Waiting for the patient worklist.'}</Text>}<Button ghost onPress={()=>onAction('patients')}>Patient directory</Button></Card>}
      {['doctor','labtech','admin'].includes(role)&&<Card title={role==='labtech'?'Tests needing attention':'Results awaiting review'}>{work.labs.slice(0,3).map(l=><View key={l.id} style={local.item}><Text style={styles.heading}>{l.test_type}</Text><Text style={styles.muted}>{l.patient_id}</Text><Badge value={l.critical?'urgent':l.status}/></View>)}{!work.labs.length&&<Text style={styles.muted}>{lastUpdated?'No outstanding results in this worklist.':'Waiting for the laboratory worklist.'}</Text>}<Button ghost onPress={()=>onAction('lab')}>Open laboratory</Button></Card>}
      {role==='pharmacist'&&<><Card title="Ready to dispense">{work.prescriptions.slice(0,3).map(p=><View key={p.id} style={local.item}><Text style={styles.heading}>{p.medication}</Text><Text style={styles.subtitle}>{p.patient_id} · {p.instructions}</Text></View>)}{!work.prescriptions.length&&<Text style={styles.muted}>No current prescriptions in the loaded worklist.</Text>}<Button ghost onPress={()=>onAction('pharmacy')}>Open dispensing</Button></Card><Card title="Stock attention">{work.stock.slice(0,3).map(b=><View key={b.id}><Text style={styles.heading}>{b.medication}</Text><Text style={styles.subtitle}>{b.quantity} units · expires {b.expires_on}</Text></View>)}{!work.stock.length&&<Text style={styles.muted}>No stock flags in the loaded worklist.</Text>}<Button ghost onPress={()=>onAction('stock')}>Review batches</Button></Card></>}
      {role==='admin'&&<Card title="Institution overview"><Text style={styles.subtitle}>{work.visits.length} open visits in the loaded queue</Text><Text style={styles.subtitle}>{work.links.length} patient accounts awaiting identity verification</Text><Button ghost onPress={()=>onAction('team')}>Review team & access</Button><Button ghost onPress={()=>onAction('billing')}>Invoices & receipts</Button></Card>}
    </>}
  </View>
}
const local=StyleSheet.create({hero:{backgroundColor:'#e9f0e4',borderRadius:22,borderWidth:1,borderColor:'#d7e2cf',padding:22,gap:12},eyebrow:{fontSize:10,letterSpacing:2,fontWeight:'700',color:'#44705b'},actions:{flexDirection:'row',gap:12,flexWrap:'wrap'},action:{flex:1,minWidth:120,minHeight:64,padding:16,borderRadius:14,backgroundColor:'#fff',borderWidth:1,borderColor:'#dce5d8',justifyContent:'center'},actionText:{color:'#176b59',fontWeight:'700',fontSize:14},stat:{flex:1,minWidth:120,padding:18,borderWidth:1,borderColor:'#dce5d8',borderRadius:16,backgroundColor:'#fff'},count:{fontSize:30,fontWeight:'700',color:'#1b3b2e'},item:{gap:8,borderBottomWidth:1,borderBottomColor:'#edf1e9',paddingBottom:12}})
