import { useState } from 'react'
import useAuthStore from '../stores/authStore'
import useRecords from '../hooks/useRecords'
import { Panel,Field,Status,Feedback,Empty,ActionForm } from '../components/ui/CarelineUI'
import { fullName,isCurrentPrescription,documentUrl,money } from '../lib/careline'
import PatientCard from '../components/PatientCard'
import { Link } from 'react-router-dom'
export default function CarePortalPage(){
 const user=useAuthStore(s=>s.user),patients=useRecords('patients',{field:'auth_user_id',value:user.id}),facilities=useRecords('facilities',{field:null}),p=patients.rows[0]
 const visits=useRecords('visits',{field:'patient_id',value:p?.id,enabled:!!p}),labs=useRecords('lab_results',{field:'patient_id',value:p?.id,order:'uploaded_at',enabled:!!p}),rx=useRecords('prescriptions',{field:'patient_id',value:p?.id,enabled:!!p}),appointments=useRecords('appointments',{field:'patient_id',value:p?.id,enabled:!!p}),invoices=useRecords('invoices',{field:'patient_id',value:p?.id,enabled:!!p})
 const [tab,setTab]=useState('overview'),[error,setError]=useState(''),[appointmentFacility,setAppointmentFacility]=useState(''),[linkFacility,setLinkFacility]=useState('')
 if(!p)return <div className="care-stack"><h1>Your Careline account</h1><Feedback data={patients}/>{!patients.loading&&<><Panel title="Connect your existing patient record"><p>Enter the ID on your Careline card. The registering facility will verify your identity before connecting the record.</p><ActionForm action="request_link" facilityId={linkFacility} label="Request account linking"><Field label="Registering facility" value={linkFacility} onChange={e=>setLinkFacility(e.target.value)} required options={[{value:'',label:'Choose facility'},...facilities.rows.map(f=>({value:f.id,label:f.name}))]}/><Field label="Patient ID" name="patient_id" required placeholder="CL-… or MT-…"/></ActionForm></Panel><Panel title="Institution staff"><p>Your institution administrator can invite your verified email. Refresh your access after accepting an invitation.</p><button className="btn btn-primary" onClick={()=>useAuthStore.getState().refreshContext()}>Refresh institution access</button><Link className="btn btn-ghost" to="/institutions">Apply for an institution →</Link></Panel></>}</div>
 return <div className="care-stack"><div className="care-welcome"><div><p className="care-eyebrow">MY CARELINE</p><h1>Hello, {p.first_name}.</h1><p>Your care history, prescriptions and next visits, together.</p></div><Link className="btn btn-primary" to="/institutions">Find an institution</Link></div><div className="care-tabs">{[['overview','Overview'],['records','My records'],['appointments','Appointments'],['card','My patient card']].map(([k,l])=><button key={k} aria-pressed={tab===k} onClick={()=>setTab(k)}>{l}</button>)}</div>{error&&<p className="care-error" role="alert">{error}</p>}
 {tab==='overview'&&<><div className="care-grid"><Panel title="Current prescriptions"><Feedback data={rx}/>{rx.rows.filter(p=>isCurrentPrescription(p)).map(r=><div className="care-history" key={r.id}><strong>{r.medication}</strong><p>{r.instructions}</p><p>From {r.starts_on}{r.ends_on?' until '+r.ends_on:''}</p></div>)}{!rx.rows.some(p=>isCurrentPrescription(p))&&<Empty>No current prescriptions recorded.</Empty>}</Panel><Panel title="Next visits"><Feedback data={appointments}/>{appointments.rows.filter(a=>['requested','confirmed'].includes(a.status)).map(a=><div className="care-history" key={a.id}><strong>{new Date(a.scheduled_at).toLocaleString()}</strong><p>{facilities.rows.find(f=>f.id===a.facility_id)?.name}</p><Status value={a.status}/></div>)}</Panel></div><Panel title="Follow-up instructions">{visits.rows.filter(v=>v.follow_up_date).map(v=><div className="care-history" key={v.id}><strong>Return on {v.follow_up_date}</strong><p>{v.notes}</p></div>)}{!visits.rows.some(v=>v.follow_up_date)&&<Empty>Your care team has not recorded a follow-up date.</Empty>}</Panel></>}
 {tab==='records'&&<><Panel title="Visit history"><Feedback data={visits}/>{visits.rows.map(v=><div className="care-history" key={v.id}><strong>{new Date(v.date).toLocaleDateString()} · {facilities.rows.find(f=>f.id===v.facility_id)?.name||'Care institution'}</strong><p>{v.diagnosis||'Assessment not recorded'}</p><p className="care-prewrap">{v.notes}</p>{v.prescription&&<p>Historical prescription: {v.prescription}</p>}</div>)}</Panel><Panel title="Laboratory results"><Feedback data={labs}/>{labs.rows.map(l=><div className="care-history" key={l.id}><strong>{l.test_type}</strong> <Status value={l.status}/><p>{l.summary}</p>{(l.storage_path||l.file_url)&&<button className="btn btn-ghost" onClick={async()=>{try{window.open(await documentUrl(l),'_blank','noopener,noreferrer')}catch(e){setError(e.message)}}}>View attachment</button>}</div>)}</Panel><Panel title="Your invoices"><Feedback data={invoices}/>{invoices.rows.map(i=><div className="care-list-row" key={i.id}><div><strong>{i.description}</strong><p>{money(i.total)}</p></div><Status value={i.status}/></div>)}</Panel></>}
 {tab==='appointments'&&<Panel title="Request an appointment"><p>Your request becomes a booking after the institution confirms it.</p><ActionForm action="appointment" facilityId={appointmentFacility} initial={{patient_id:p.id}} label="Send request" transform={p=>({...p,scheduled_at:new Date(p.scheduled_at).toISOString()})}><Field label="Institution" value={appointmentFacility} onChange={e=>setAppointmentFacility(e.target.value)} required options={[{value:'',label:'Select institution'},...facilities.rows.filter(f=>f.status==='active').map(f=>({value:f.id,label:f.name}))]}/><Field label="Preferred date and time (local time)" name="scheduled_at" type="datetime-local" required/><Field label="Reason / service" name="reason" required/></ActionForm></Panel>}
 {tab==='card'&&<PatientCard patient={p}/>}</div>
}
