import { useState } from 'react'
import useAuthStore from '../stores/authStore'
import useRecords from '../hooks/useRecords'
import { rpc } from '../lib/careline'
import { Panel,Field,Feedback,Status,ActionButton } from '../components/ui/CarelineUI'
const roles=['nurse','doctor','labtech','pharmacist','admin']
export default function CareStaffPage(){
 const {user,refreshContext}=useAuthStore(),f=user.user_metadata.facility_id,members=useRecords('facility_members'),profiles=useRecords('profiles',{field:null}),invites=useRecords('staff_invitations'),links=useRecords('record_links'),audit=useRecords('audit_events')
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 async function invite(e){e.preventDefault();if(busy)return;const form=e.currentTarget,p=Object.fromEntries(new FormData(form));setBusy(true);setError('');try{await rpc('careline_invite_staff',{f,staff_email:p.email,staff_role:p.role});form.reset();setMessage('Invitation saved. Ask the staff member to register with this email, verify it, then sign in. Email delivery is not automated.');invites.refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function update(member,role,active){if(busy)return;setBusy(true);setError('');try{await rpc('careline_manage_member',{f,member_id:member.user_id,member_role:role,enabled:active});members.refresh();if(member.user_id===user.id)await refreshContext()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="care-stack"><div><p className="care-eyebrow">INSTITUTION ADMINISTRATION</p><h1>The right access for each colleague.</h1><p>Nurses can handle registration, arrivals and triage. A separate receptionist account is not required.</p></div>{error&&<p className="care-error" role="alert">{error}</p>}{message&&<p className="care-notice" role="status">{message}</p>}<div className="care-grid"><Panel title="Invite staff"><form className="care-form" onSubmit={invite}><Field label="Staff email" name="email" type="email" required/><Field label="Responsibility" name="role" options={roles}/><button className="btn btn-primary" disabled={busy}>Save invitation</button></form><Feedback data={invites}/>{invites.rows.map(i=><div className="care-history" key={i.id}><strong>{i.email}</strong><p>{i.role} · {i.accepted_at?'Accepted':'Awaiting verified registration'}</p><small>Expires {new Date(i.expires_at).toLocaleDateString()}</small></div>)}</Panel><Panel title="Institution team"><Feedback data={members}/>{members.rows.map(m=>{const p=profiles.rows.find(p=>p.id===m.user_id);return <div className="care-history" key={m.user_id}><strong>{p?.name||m.user_id}</strong><p>{p?.email}</p><Status value={m.active?'active':'inactive'}/><Field label="Role" value={m.role} disabled={busy} options={roles} onChange={e=>update(m,e.target.value,m.active)}/><button className="btn btn-ghost" disabled={busy} onClick={()=>update(m,m.role,!m.active)}>{m.active?'Deactivate membership':'Activate reviewed membership'}</button></div>})}</Panel></div><Panel title="Patient account link requests"><p>Verify identity in person before approving. Matching a phone number is insufficient.</p><Feedback data={links}/>{links.rows.filter(l=>l.status==='pending').map(l=><div className="care-list-row" key={l.id}><div><strong>{l.patient_id}</strong><p>Requesting account: {l.requested_by}</p></div><ActionButton action="approve_link" initial={{id:l.id}}>Approve verified identity</ActionButton></div>)}</Panel><Panel title="Recent change audit"><Feedback data={audit}/>{audit.rows.slice(0,30).map(a=><div className="care-list-row" key={a.id}><div><strong>{a.entity} · {a.action}</strong><p>{a.entity_id}</p><small>Actor {a.actor_id||'System'} · {new Date(a.created_at).toLocaleString()}</small></div></div>)}</Panel></div>
}
