import useTeam from '../hooks/useTeam'
import { useState } from 'react'
import useAuthStore from '../stores/authStore'
import useRecords from '../hooks/useRecords'
import { Panel,Status,Field,Feedback,Empty,ActionForm,ActionButton } from '../components/ui/CarelineUI'
import { documentUrl } from '../lib/careline'
import { Link } from 'react-router-dom'
export default function CareLabPage(){
 const team=useTeam()
 const labs=useRecords('lab_results',{order:'uploaded_at'}), role=useAuthStore(s=>s.role),[filter,setFilter]=useState('all'),[error,setError]=useState('')
 const technician=['admin','labtech'].includes(role),clinician=['admin','doctor'].includes(role)
 return <div className="care-stack"><div className="care-page-title"><div><p className="care-eyebrow">LABORATORY</p><h1>From request to reviewed result.</h1><p>Specimen processing, result completion and clinician review are separate steps.</p></div>{technician&&<Link className="btn btn-primary" to="/lab/upload">Upload standalone result</Link>}</div><Panel title="Laboratory worklist"><Field label="Filter by stage" value={filter} onChange={e=>setFilter(e.target.value)} options={['all','requested','processing','completed','reviewed']}/><Feedback data={labs}/>{error&&<p className="care-error" role="alert">{error}</p>}{labs.rows.filter(l=>filter==='all'||l.status===filter).map(l=><article key={l.id} className="care-history"><div className="care-list-row"><div><h3>{l.test_type}</h3><p>{l.patient_id} · {new Date(l.uploaded_at).toLocaleString()}</p></div><Status value={l.status}/></div>{l.critical&&l.status!=='reviewed'&&<div className="care-error"><strong>Urgent clinician review requested</strong><p>{l.critical_reason}</p><p>Contact the responsible clinician directly as well as recording the escalation.</p></div>}{l.summary&&<p className="care-prewrap">{l.summary}</p>}{technician&&l.status==='requested'&&<ActionForm action="lab_progress" initial={{id:l.id}} label="Start processing"><Field label="Specimen reference" name="specimen_reference" required/></ActionForm>}{technician&&['requested','processing'].includes(l.status)&&<ActionForm action="lab_complete" initial={{id:l.id}} label="Complete result"><Field label="Validated findings / result" name="summary" type="textarea" required/></ActionForm>}{(technician||clinician)&&l.status==='completed'&&<details className="care-disclosure"><summary>Escalate for urgent review</summary><ActionForm action="lab_escalate" initial={{id:l.id}} label="Assign urgent review"><Field label="Reason for escalation" name="reason" type="textarea" required/><Field label="Responsible clinician" name="assigned_to" required options={[{value:'',label:'Choose clinician'},...team.rows.filter(m=>['admin','doctor'].includes(m.role)).map(m=>({value:m.id,label:m.name}))]}/></ActionForm></details>}{clinician&&l.status==='completed'&&<ActionButton action="lab_review" initial={{id:l.id}}>Mark reviewed</ActionButton>}{(l.storage_path||l.file_url)&&<button className="btn btn-ghost" onClick={async()=>{try{const url=await documentUrl(l);window.open(url,'_blank','noopener,noreferrer')}catch(e){setError(e.message)}}}>Open private attachment</button>}{l.reviewed_by&&<p className="care-muted">Reviewed {new Date(l.notified_at).toLocaleString()}</p>}</article>)}{!labs.rows.length&&!labs.loading&&<Empty>No laboratory requests or results.</Empty>}</Panel></div>
}
