import { Link,useParams } from 'react-router-dom'
import { useState } from 'react'
import useAuthStore from '../stores/authStore'
import useRecords from '../hooks/useRecords'
import { Panel,Field,Status,Feedback,Empty,ActionForm,ActionButton } from '../components/ui/CarelineUI'
import { fullName,ageLabel,isCurrentPrescription } from '../lib/careline'
import PatientCard from '../components/PatientCard'
export default function CarePatientPage(){
 const {id}=useParams(),{role,user}=useAuthStore()
 const patient=useRecords('patients',{field:'id',value:id}), visits=useRecords('visits',{field:'patient_id',value:id}), labs=useRecords('lab_results',{field:'patient_id',value:id,order:'uploaded_at'}), observations=useRecords('observations',{field:'patient_id',value:id,order:'recorded_at'}), prescriptions=useRecords('prescriptions',{field:'patient_id',value:id}),facilities=useRecords('facilities',{field:null})
 const [tab,setTab]=useState('visit'),p=patient.rows[0], f=user?.user_metadata?.facility_id
 const current=visits.rows.find(v=>v.facility_id===f&&!['completed','cancelled'].includes(v.status))
 const clinical=['admin','doctor'].includes(role)
 if(!p)return <Panel title="Patient record"><Feedback data={patient}/>{!patient.loading&&!patient.error&&<Empty>Record unavailable. Check your facility access and patient ID.</Empty>}<Link to="/patients">Back to directory</Link></Panel>
 return <div className="care-stack"><Link to="/patients" className="care-muted">← Patient directory</Link><div className="care-patient-header"><div className="care-avatar">{p.first_name?.[0]}{p.last_name?.[0]}</div><div><p className="care-eyebrow">{p.id}</p><h1>{fullName(p)}</h1><p>{ageLabel(p.date_of_birth)} years · {p.gender||'Gender not recorded'} · {p.phone||'No contact phone'}</p></div><button className="btn btn-ghost" onClick={()=>window.print()}>Print summary</button></div><div className="care-alert-strip"><span><strong>Reported allergies:</strong> {p.allergies||'Unknown — confirm with patient'}</span><span><strong>Blood group:</strong> {p.blood_group||'Unknown'}</span></div>
 <div className="care-tabs" role="tablist">{[['visit','Current visit'],['history','Care history'],['prescriptions','Prescriptions'],['referral','Refer patient'],['card','Patient card']].map(([key,label])=><button key={key} role="tab" aria-selected={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</div>
 {tab==='visit'&&<><Panel title={current?'Current visit':'Register an arrival'}><Feedback data={visits}/>{!current?<ActionForm action="arrive" initial={{patient_id:id}} label="Add to waiting list"><div className="care-grid"><Field label="Priority assigned by staff" name="priority" options={['routine','urgent','emergency']}/><Field label="Reason for visit" name="notes" type="textarea"/></div></ActionForm>:<div className="care-stack"><div className="care-list-row"><div><Status value={current.status}/> <Status value={current.priority}/><p>Arrived {new Date(current.date).toLocaleString()}</p></div></div><ActionForm key={current.id+':'+current.version} action="visit" initial={{id:current.id,version:current.version}} label="Update visit"><div className="care-grid"><Field label="Next stage" name="status" defaultValue={current.status} options={clinical?['waiting','triage','consultation','awaiting_tests','completed','cancelled']:['waiting','triage','consultation','cancelled']}/>{clinical&&<Field label="Follow-up date" name="follow_up_date" type="date" defaultValue={current.follow_up_date||''}/>}</div>{clinical&&<Field label="Diagnosis / assessment" name="diagnosis" type="textarea" defaultValue={current.diagnosis||''}/>}<Field label={clinical?'Consultation notes':'Nursing / reception notes'} name="notes" type="textarea" defaultValue={current.notes||''}/><p className="care-muted">Closing the visit locks these notes. Check your entry before completing it.</p></ActionForm></div>}</Panel>
 {current&&<div className="care-grid"><Panel title="Record observations"><ActionForm action="observe" initial={{visit_id:current.id}} label="Save observations"><div className="care-grid"><Field label="Temperature °C" name="temperature" type="number" step="0.1" min="20" max="50"/><Field label="Pulse / min" name="pulse" type="number" min="10" max="350"/><Field label="Systolic mmHg" name="systolic" type="number" min="20" max="350"/><Field label="Diastolic mmHg" name="diastolic" type="number" min="10" max="250"/><Field label="Weight kg" name="weight" type="number" step="0.01" min="0.01"/><Field label="SpO₂ %" name="spo2" type="number" min="0" max="100"/></div><Field label="Observation notes" name="notes" type="textarea"/></ActionForm></Panel><Panel title="Laboratory">{clinical&&<ActionForm action="lab_order" initial={{patient_id:id,visit_id:current.id}} label="Request test"><Field label="Test name" name="test_type" required/></ActionForm>}<Feedback data={labs}/>{labs.rows.map(l=><div className="care-list-row" key={l.id}><div><strong>{l.test_type}</strong><p>{l.summary||'Awaiting laboratory result'}</p><Status value={l.status}/></div>{clinical&&l.status==='completed'&&<ActionButton action="lab_review" initial={{id:l.id}} facilityId={l.facility_id}>Review</ActionButton>}</div>)}</Panel></div>}</>}
 {tab==='history'&&<><Panel title="Visits"><Feedback data={visits}/>{visits.rows.map(v=><article className="care-history" key={v.id}><div><strong>{new Date(v.date).toLocaleDateString()}</strong> <Status value={v.status}/></div><p>{v.diagnosis||'No diagnosis recorded'}</p><p className="care-prewrap">{v.notes}</p>{v.prescription&&<p>Historical prescription text: {v.prescription}</p>}{v.follow_up_date&&<p>Follow-up: {v.follow_up_date}</p>}</article>)}{!visits.rows.length&&<Empty>No visits recorded.</Empty>}</Panel><Panel title="Observation history"><Feedback data={observations}/>{observations.rows.map(o=><div className="care-history" key={o.id}><strong>{new Date(o.recorded_at).toLocaleString()}</strong><p>Temperature {o.temperature??'—'} °C · BP {o.systolic??'—'}/{o.diastolic??'—'} · Pulse {o.pulse??'—'} · Weight {o.weight??'—'} kg · SpO₂ {o.spo2??'—'}%</p><p>{o.notes}</p></div>)}</Panel></>}
 {tab==='prescriptions'&&<div className="care-grid">{clinical&&<Panel title="New prescription"><ActionForm action="prescribe" initial={{patient_id:id}} label="Save prescription"><Field label="Medicine (generic name and strength)" name="medication" required/><Field label="Dose, route, frequency and duration" name="instructions" type="textarea" required/><div className="care-grid"><Field label="Quantity to dispense" name="quantity" type="number" min="1" required/><Field label="Treatment end date" name="ends_on" type="date"/></div><Field label="Dispensing facility" name="pharmacy_id" options={[{value:'',label:'This facility'},...facilities.rows.filter(f=>f.status==='active'&&f.facility_type!=='laboratory').map(f=>({value:f.id,label:f.name}))]}/><p className="care-muted">Confirm allergies and the prescription clinically. Automated drug interaction checking is not enabled.</p></ActionForm></Panel>}<Panel title="Prescription history"><Feedback data={prescriptions}/>{prescriptions.rows.map(rx=><div className="care-history" key={rx.id}><strong>{rx.medication}</strong> <Status value={isCurrentPrescription(rx)?'active':rx.status==='active'?'ended':rx.status}/><p>{rx.instructions}</p><p>Quantity: {rx.quantity} · {rx.starts_on} → {rx.ends_on||'End date not recorded'}</p>{clinical&&rx.status==='active'&&<ActionButton action="stop_prescription" initial={{id:rx.id}}>Stop prescription</ActionButton>}</div>)}</Panel></div>}
 {tab==='referral'&&<Panel title="Refer to another institution"><ActionForm action="refer" initial={{patient_id:id}} label="Send referral" transform={p=>({...p,consent_recorded:p.consent_recorded==='on'})}><Field label="Receiving institution" name="target_facility_id" required options={[{value:'',label:'Choose institution'},...facilities.rows.filter(x=>x.id!==f&&x.status==='active').map(x=>({value:x.id,label:x.name}))]}/><Field label="Reason and referral summary" name="reason" type="textarea" required/><label className="care-checkbox"><input name="consent_recorded" type="checkbox" required/> Patient or authorised guardian agrees to share this referral and registration details.</label><p className="care-muted">The receiving institution receives this summary. Other clinical records remain with the originating institution.</p></ActionForm></Panel>}
 {tab==='card'&&<PatientCard patient={p}/>}
 </div>
}
