import { useState } from 'react'
import useAuthStore from '../stores/authStore'
import useRecords from '../hooks/useRecords'
import { rpc } from '../lib/careline'
import { Panel,Field,Feedback,Status,Empty } from '../components/ui/CarelineUI'
export default function InstitutionsPage(){
 const {isOperator}=useAuthStore(),data=useRecords('facilities',{field:null}),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('')
 async function submit(e){e.preventDefault();if(busy)return;const form=e.currentTarget;setBusy(true);setError('');try{await rpc('careline_apply_facility',{payload:Object.fromEntries(new FormData(form))});form.reset();setSuccess('Application received. A Careline operator must review it before staff access is activated.');data.refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="care-stack"><div><p className="care-eyebrow">CARELINE NETWORK</p><h1>Care, closer to your community.</h1><p>Find participating institutions or apply to bring your facility onto Careline.</p></div><Panel title="Institutions"><Field label="Search services, institution or location" value={search} onChange={e=>setSearch(e.target.value)}/><Feedback data={data}/><div className="care-grid">{data.rows.filter(f=>[f.name,f.region,f.location,f.services].join(' ').toLowerCase().includes(search.toLowerCase())).map(f=><article className="care-facility" key={f.id}><Status value={f.status}/><h3>{f.name}</h3><p>{f.facility_type.replaceAll('_',' ')} · {f.region}</p><p>{f.location}</p><p>{f.services||'Contact the facility for available services.'}</p><p>{f.opening_hours||'Opening hours not provided'}</p>{f.phone&&<a href={'tel:'+f.phone}>{f.phone}</a>}{isOperator&&f.status==='pending'&&<button className="btn btn-primary" disabled={busy} onClick={async()=>{if(!confirm('Have you verified this institution and its owner? This will activate their administrator membership.'))return;setBusy(true);try{await rpc('careline_approve_facility',{f:f.id});data.refresh()}catch(e){setError(e.message)}finally{setBusy(false)}}}>Approve verified institution</button>}</article>)}</div>{!data.rows.length&&<Empty>No institutions are available yet.</Empty>}</Panel>
 <Panel title="Apply for your institution"><form className="care-form" onSubmit={submit}><fieldset disabled={busy}><div className="care-grid"><Field label="Institution name" name="name" required/><Field label="Institution type" name="facility_type" options={['health_centre','clinic','hospital','laboratory','pharmacy']}/><Field label="Registration / licensing reference" name="registration_number" required/><Field label="Region" name="region" required/><Field label="Address, neighbourhood or landmark" name="location" required/><Field label="Contact phone" name="phone" required/><Field label="Services offered" name="services" type="textarea"/><Field label="Opening hours" name="opening_hours" placeholder="Mon–Fri 08:00–17:00"/></div><button className="btn btn-primary">{busy?'Submitting…':'Submit for review'}</button></fieldset></form>{error&&<p className="care-error" role="alert">{error}</p>}{success&&<p role="status" className="care-notice">{success}</p>}</Panel></div>
}
