import { useState } from 'react'
import useRecords from '../hooks/useRecords'
import { money,isCurrentPrescription } from '../lib/careline'
import { Panel,Feedback,Empty,Field,Status,ActionForm } from '../components/ui/CarelineUI'
import useAuthStore from '../stores/authStore'
export default function PharmacyPage(){
 const f=useAuthStore(s=>s.user?.user_metadata?.facility_id),stock=useRecords('stock_batches'),rx=useRecords('prescriptions',{field:null}),dispensed=useRecords('dispensings'),[tab,setTab]=useState('dispense')
 const today=new Date().toISOString().slice(0,10),expiring=stock.rows.filter(b=>b.expires_on<=new Date(Date.now()+30*86400000).toISOString().slice(0,10))
 const assigned=rx.rows.filter(p=>p.pharmacy_id===f||(!p.pharmacy_id&&p.facility_id===f))
 return <div className="care-stack"><div><p className="care-eyebrow">PHARMACY</p><h1>Every prescription. Every batch.</h1><p>Track partial dispensing, available stock and expiry dates in one place.</p></div><div className="care-stats"><div><span>Assigned prescriptions</span><strong>{assigned.filter(p=>isCurrentPrescription(p)).length}</strong></div><div><span>Stock batches</span><strong>{stock.rows.length}</strong></div><div><span>Expired or due within 30 days</span><strong>{expiring.length}</strong></div></div><div className="care-tabs">{[['dispense','Dispense'],['stock','Stock & expiry'],['history','Dispensing history']].map(([k,l])=><button key={k} aria-pressed={tab===k} onClick={()=>setTab(k)}>{l}</button>)}</div>
 {tab==='dispense'&&<Panel title="Prescriptions assigned to this pharmacy"><Feedback data={rx}/><Feedback data={stock}/>{assigned.filter(p=>isCurrentPrescription(p)).map(p=><div className="care-history" key={p.id}><h3>{p.medication}</h3><p>Patient: {p.patient_id}</p><p>{p.instructions}</p><p>Prescribed quantity: {p.quantity}. Confirm the patient's Careline ID before dispensing.</p><ActionForm action="dispense" initial={{prescription_id:p.id}} label="Record dispensing"><div className="care-grid"><Field label="Available batch" name="batch_id" required options={[{value:'',label:'Choose matching medicine'},...stock.rows.filter(b=>b.quantity>0&&b.expires_on>today&&b.medication.trim().toLowerCase()===p.medication.trim().toLowerCase()).map(b=>({value:b.id,label:b.batch_number+' · '+b.quantity+' available · expires '+b.expires_on}))]}/><Field label="Quantity dispensed now" name="quantity" type="number" min="1" max={p.quantity} required/></div></ActionForm></div>)}{!assigned.length&&<Empty>No prescriptions assigned. The clinician selects the dispensing facility when prescribing.</Empty>}</Panel>}
 {tab==='stock'&&<div className="care-grid"><Panel title="Receive a stock batch"><ActionForm action="stock" label="Receive stock"><Field label="Medicine (generic name and strength)" name="medication" required/><Field label="Batch number" name="batch_number" required/><Field label="Expiry date" name="expires_on" type="date" required/><div className="care-grid"><Field label="Quantity received" name="quantity" type="number" min="1" required/><Field label="Unit selling price, FCFA" name="unit_price" type="number" min="0" required/></div></ActionForm></Panel><Panel title="Available stock"><Feedback data={stock}/>{stock.rows.map(b=><div className="care-history" key={b.id}><strong>{b.medication}</strong><p>{b.batch_number} · {b.quantity} units · {money(b.unit_price)} / unit</p><p>Expires {b.expires_on} {b.expires_on<=today&&<Status value="expired"/>}{b.quantity<=5&&<Status value="low_stock"/>}</p></div>)}</Panel></div>}
 {tab==='history'&&<Panel title="Dispensing history"><Feedback data={dispensed}/>{dispensed.rows.map(d=><div className="care-list-row" key={d.id}><div><strong>{d.patient_id}</strong><p>{d.quantity} units · {new Date(d.created_at).toLocaleString()}</p><small>Prescription {d.prescription_id}</small></div><strong>{money(d.quantity*d.unit_price)}</strong></div>)}{!dispensed.rows.length&&<Empty>No dispensing recorded.</Empty>}</Panel>}
 </div>
}
