import React,{useState,useEffect,useRef,useCallback} from 'react'
import {View,Text,ScrollView,RefreshControl,TouchableOpacity,Linking,Alert,TextInput,Image,Share} from 'react-native'
import {useSafeAreaInsets} from 'react-native-safe-area-context'
import {Picker} from '@react-native-picker/picker'
import {supabase} from '../lib/supabase'
import {command,rpc,money,currentPrescription,normalizePhone} from '../lib/careline'
import {Button,Card,Badge,FormModal,styles} from '../components/CareUI'
import NativePatientCard from '../components/NativePatientCard'
import CareCoordination from '../components/CareCoordination'
import CareTasks,{taskFields} from '../components/CareTasks'
import NativeDashboard from '../components/NativeDashboard'
import NativeResultUpload from '../components/NativeResultUpload'
import {loadDashboard,connected} from '../lib/dashboard.mjs'
import {openNativeDocument} from '../lib/nativeDocuments'
import NetInfo,{useNetInfo} from '@react-native-community/netinfo'
const choices=(rows,label)=>[{value:'',label:'Choose…'},...rows.map(r=>({value:r.id,label:label(r)}))]
const patientLabel=p=>[p.first_name,p.last_name].filter(Boolean).join(' ')+' · '+p.id
const intakeFields=[['first_name','First name'],['last_name','Last name'],['date_of_birth','Birth date, optional','date'],['gender','Sex / gender','select',[{value:'',label:'Unknown'},'Male','Female','Other']],['phone','Contact phone (may be shared)'],['region','Region'],['village','Village / neighbourhood'],['blood_group','Blood group','select',[{value:'',label:'Unknown'},'A+','A-','B+','B-','AB+','AB-','O+','O-']],['allergies','Reported allergies'],['next_of_kin','Next of kin and phone']]
export default function CareWorkspaceScreen({user,context,refreshContext}){
 const {role,facility_id:f}=context,insets=useSafeAreaInsets(),clinical=['admin','doctor'].includes(role),nursing=['admin','doctor','nurse'].includes(role),pharmacy=['admin','pharmacist'].includes(role),labtech=['admin','labtech'].includes(role)
 const tabs=role==='patient'?['My care','Care plan','Institutions','Account']:['Today','Tasks',...(nursing?['Patients','Appointments','Referrals']:[]),...(nursing||labtech?['Laboratory']:[]),...(pharmacy?['Pharmacy','Stock']:[]),...(['admin','nurse','pharmacist'].includes(role)?['Billing']:[]),'Notice board','Institutions',...(role==='admin'?['Team']:[]),'Account']
 const primary=role==='patient'?['My care','Care plan','Institutions']:['Today',nursing?'Patients':labtech?'Laboratory':'Pharmacy','Tasks']
 const network=useNetInfo(),online=connected(network)
 const [upload,setUpload]=useState(false),[portalSection,setPortalSection]=useState('Overview'),[lastUpdated,setLastUpdated]=useState(null)
 const [patientTab,setPatientTab]=useState('Summary'),[taskHistory,setTaskHistory]=useState(false)
 const [tab,setTab]=useState(tabs[0]),[data,setData]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[form,setForm]=useState(null),[patient,setPatient]=useState(null),[search,setSearch]=useState(''),[mutating,setMutating]=useState(false),generation=useRef(0)
 useEffect(()=>setPatientTab('Summary'),[patient?.id])
 useEffect(()=>{if(tab!=='Tasks')setTaskHistory(false)},[tab])
 const records=async(table,{field='facility_id',value=f,order='created_at'}={})=>{
  let query=supabase.from(table).select('*').order(order,{ascending:false}).limit(100)
  if(field)query=query.eq(field,value)
  const {data,error}=await query;if(error)throw error;return data||[]
 }
 const reload=useCallback(async()=>{
  const run=++generation.current;setBusy(true);setError('')
  try{
   let result={}
   if(patient){
    const [visits,observations,prescriptions,labs,referrals]=await Promise.all([records('visits',{field:'patient_id',value:patient.id}),records('observations',{field:'patient_id',value:patient.id,order:'recorded_at'}),records('prescriptions',{field:'patient_id',value:patient.id}),records('lab_results',{field:'patient_id',value:patient.id,order:'uploaded_at'}),records('referrals',{field:'patient_id',value:patient.id})])
    result={visits,observations,prescriptions,labs,referrals}
   }else if(['My care','Care plan'].includes(tab)){
    const patients=await records('patients',{field:'auth_user_id',value:user.id});result.patients=patients
    if(patients[0]){
     const pid=patients[0].id
     const [visits,prescriptions,labs,appointments,invoices]=await Promise.all([records('visits',{field:'patient_id',value:pid}),records('prescriptions',{field:'patient_id',value:pid}),records('lab_results',{field:'patient_id',value:pid,order:'uploaded_at'}),records('appointments',{field:'patient_id',value:pid}),records('invoices',{field:'patient_id',value:pid})])
     Object.assign(result,{visits,prescriptions,labs,appointments,invoices})
    }
   }else if(tab==='Today'){
    result=await loadDashboard(supabase,role,f)
   }else if(tab==='Patients'){
    let query=supabase.from('patients').select('*').is('archived_at',null).order('created_at',{ascending:false}).limit(100)
    const clean=search.replace(/[^\p{L}\p{N} +.-]/gu,'').trim()
    if(clean){const parts=clean.split(/\s+/);query=parts.length>1?query.ilike('first_name','%'+parts[0]+'%').ilike('last_name','%'+parts.slice(1).join(' ')+'%'):query.or('first_name.ilike.%'+clean+'%,last_name.ilike.%'+clean+'%,id.ilike.%'+clean+'%,phone.ilike.%'+clean+'%')}
    const {data,error}=await query;if(error)throw error;result.patients=data||[]
   }else if(tab==='Laboratory')result.labs=await records('lab_results',{order:'uploaded_at'})
   else if(tab==='Pharmacy'){result.prescriptions=await records('prescriptions',{field:null});result.stock=await records('stock_batches');result.dispensings=await records('dispensings')}
   else if(tab==='Stock')result.stock=await records('stock_batches')
   else if(tab==='Appointments')result.appointments=await records('appointments')
   else if(tab==='Referrals')result.referrals=await records('referrals',{field:null})
   else if(tab==='Billing'){result.invoices=await records('invoices');result.payments=await records('payments')}
   else if(tab==='Notice board'){result.notices=await records('staff_broadcasts');result.colleagues=await rpc('careline_staff_directory',{f})}
   else if(tab==='Team'){result.members=await records('facility_members');result.profiles=await records('profiles',{field:null});result.links=await records('record_links');result.invitations=await records('staff_invitations')}
   if(role!=='patient'&&(patient||['Today','Tasks','Laboratory','Referrals'].includes(tab)))result.colleagues=await rpc('careline_staff_directory',{f})
   if(role!=='patient'&&['Today','Tasks'].includes(tab)&&!patient){const {data:tasks,error}=await supabase.from('care_tasks').select('*').eq('facility_id',f).in('status',tab==='Tasks'&&taskHistory?['completed','cancelled']:['open','in_progress','waiting']).order('due_at',{ascending:!(tab==='Tasks'&&taskHistory)}).limit(100);if(error)throw error;result.tasks=tasks||[]}
   result.facilities=await records('facilities',{field:null})
   if(run===generation.current){setData(result);setLastUpdated(new Date())}
  }catch(e){if(run===generation.current)setError(e.message)}finally{if(run===generation.current)setBusy(false)}
 },[tab,patient?.id,f,user.id,search,taskHistory])
 useEffect(()=>{setData({});setLastUpdated(null);const timer=setTimeout(reload,200);return()=>{generation.current++;clearTimeout(timer)}},[reload])
 const previousOnline=useRef(online)
 useEffect(()=>{if(online&&!previousOnline.current)reload();previousOnline.current=online},[online,reload])
 const rows=key=>data[key]||[]
 function open(title,action,fields,initial={},extra={}){setForm({title,action,fields,initial,...extra})}
 async function save(payload){
  if(!connected(await NetInfo.fetch()))throw Error('No connection. Keep this form open and retry when connected.')
  if(form.action==='register'&&payload.phone)payload.phone=normalizePhone(payload.phone)
  if(form.action==='appointment'){const date=new Date(String(payload.scheduled_at||'').replace(' ','T'));if(Number.isNaN(date.getTime()))throw Error('Enter a valid date and time.');payload.scheduled_at=date.toISOString()}
  if(form.action==='task_create'){const date=new Date(payload.due_at);if(Number.isNaN(date.getTime()))throw Error('Choose a valid due date and time.');payload.due_at=date.toISOString()}
  if(form.action==='refer')payload.consent_recorded=payload.consent_recorded==='yes'
  if(form.action==='invite'&&payload.verified!=='yes')throw Error('Confirm that this person works at your institution.');
  if(form.action==='invite')await rpc('careline_invite_staff',{f,staff_email:payload.email,staff_role:payload.role})
  else if(form.action==='apply')await rpc('careline_apply_facility',{payload})
  else if(form.action==='member')await rpc('careline_manage_member',{f,member_id:payload.user_id,member_role:payload.role,enabled:payload.active==='yes'})
  else if(form.action==='account'){const {error}=await supabase.from('profiles').update({name:payload.name}).eq('id',user.id);if(error)throw error;if(payload.password){const {error}=await supabase.auth.updateUser({password:payload.password});if(error)throw error}await refreshContext()}
  else await command(form.action,payload.target_f||f,payload)
  setMessage(form.action==='invite'?'Staff invitation saved. Share its private setup link from Team. Existing account holders can sign in normally.':form.action==='apply'?'Application submitted for operator review.':'Saved successfully.')
  await reload()
 }
 async function act(action,payload,facility=f){
  if(mutating)return;setMutating(true);setError('')
  try{if(!connected(await NetInfo.fetch()))throw Error('Reconnect before saving changes.');await command(action,facility,payload);await reload()}catch(e){setError(e.message)}finally{setMutating(false)}
 }
 async function openPatient(id){try{const {data,error}=await supabase.from('patients').select('*').eq('id',id).single();if(error)throw error;setPatient(data)}catch(e){setError(e.message)}}
 function dashboardAction(action){
  if(action==='register'){open('Register patient','register',intakeFields,{});return}
  if(action==='upload'){setUpload(true);return}
  if(role==='patient'){
   if(action==='plan'){setTab('Care plan');return}
   if(action==='book'){open('Request appointment','appointment',[['target_f','Institution','select',choices(rows('facilities').filter(x=>x.status==='active'),x=>x.name)],...appointmentFields.slice(1)],{patient_id:rows('patients')[0]?.id});return}
   setPortalSection({card:'Card',appointments:'Appointments',medicines:'Medicines',history:'History',payments:'Payments'}[action]||'Overview');return
  }
  const target={patients:'Patients',lab:'Laboratory',tasks:'Tasks',appointments:'Appointments',pharmacy:'Pharmacy',stock:'Stock',billing:'Billing',team:'Team'}[action]
  if(target&&tabs.includes(target))setTab(target)
 }
 const appointmentFields=[['patient_id','Patient Careline ID'],['scheduled_at','Date and time (local)','datetime'],['reason','Reason / service']]
 const activeVisit=rows('visits').find(v=>v.facility_id===f&&!['completed','cancelled'].includes(v.status))
 const labCard=l=><Card key={l.id} title={l.test_type}><Text style={styles.muted}>{l.patient_id}</Text><Badge value={l.status}/>{l.summary&&<Text style={styles.subtitle}>{l.summary}</Text>}{labtech&&l.status==='requested'&&<Button ghost onPress={()=>open('Start processing','lab_progress',[['specimen_reference','Specimen reference']],{id:l.id})}>Start processing</Button>}{labtech&&['requested','processing'].includes(l.status)&&<Button onPress={()=>open('Complete result','lab_complete',[['summary','Validated result / findings','textarea']],{id:l.id})}>Complete result</Button>}{l.critical&&<Text style={styles.error}>Urgent clinical review: {l.critical_reason}</Text>}{(labtech||clinical)&&l.status==='completed'&&<Button ghost onPress={()=>open('Escalate urgent result','lab_escalate',[['reason','Reason for urgent review','textarea'],['assigned_to','Responsible clinician','select',choices(rows('colleagues').filter(m=>['admin','doctor'].includes(m.role)),m=>m.name)]],{id:l.id,target_f:l.facility_id},{description:'Contact the responsible clinician directly as well. This task does not send an emergency alert.'})}>Escalate to clinician</Button>}{clinical&&l.status==='completed'&&<Button disabled={mutating} onPress={()=>act('lab_review',{id:l.id},l.facility_id)}>Mark reviewed</Button>}{(l.storage_path||l.file_url)&&<Button ghost onPress={async()=>{try{await openNativeDocument(l)}catch(e){setError(e.message)}}}>Open private attachment</Button>}</Card>
 return <View style={[styles.page,{paddingTop:insets.top}]}><View style={{paddingHorizontal:20,paddingTop:12,paddingBottom:5}}><View style={styles.row}><View style={{flexDirection:'row',alignItems:'center',gap:6}}><Image source={require('../../assets/careline-mark-v2.png')} style={{width:32,height:32}} accessibilityLabel="Careline logo"/><Text style={[styles.title,{fontSize:26}]}>careline<Text style={{color:'#bd7652'}}>+</Text></Text></View><Text style={[styles.muted,{flexShrink:1,textAlign:'right'}]}>{role==='nurse'?'Nursing & reception':role}</Text></View>{context.memberships.length>1?<Picker selectedValue={f} onValueChange={async value=>{if(value===f)return;try{await rpc('careline_switch_facility',{f:value});await refreshContext()}catch(e){setError(e.message)}}}>{context.memberships.map(m=><Picker.Item key={m.facility_id} label={m.name} value={m.facility_id}/>)}</Picker>:<Text style={styles.muted}>{context.memberships[0]?.name||'Your care, connected'}</Text>}</View>
 <ScrollView contentContainerStyle={[styles.content,{paddingBottom:insets.bottom+35}]} refreshControl={<RefreshControl refreshing={busy} onRefresh={reload}/>} keyboardShouldPersistTaps="handled">
 {!online&&<Text accessibilityRole="alert" style={styles.error}>Connection lost. Loaded records may be out of date. Keep forms open and reconnect before saving.</Text>}
 {error&&<Text accessibilityRole="alert" style={styles.error}>{error}</Text>}{message&&<Text style={styles.subtitle}>{message}</Text>}
 {patient?<><Button ghost onPress={()=>setPatient(null)}>← Back to patients</Button><Text style={styles.title}>{patient.first_name} {patient.last_name}</Text><Text selectable style={styles.muted}>{patient.id}</Text><Card title="Check before care"><Text style={styles.subtitle}>Reported allergies: {patient.allergies||'Unknown — confirm with patient'}</Text><Text style={styles.subtitle}>Blood group: {patient.blood_group||'Unknown'}</Text></Card>
 <ScrollView horizontal showsHorizontalScrollIndicator={false}>{['Summary','Current visit','History','Care plan'].map(t=><TouchableOpacity key={t} accessibilityRole="button" accessibilityState={{selected:patientTab===t}} onPress={()=>setPatientTab(t)} style={[styles.tab,patientTab===t&&styles.activeTab]}><Text style={[styles.tabText,patientTab===t&&styles.activeText]}>{t}</Text></TouchableOpacity>)}</ScrollView>
 {patientTab==='Summary'&&<><Card title="At a glance"><Text style={styles.subtitle}>{activeVisit?'Current visit: '+activeVisit.status.replaceAll('_',' '):'No active visit'}</Text>{rows('observations')[0]&&<Text style={styles.subtitle}>Latest observations · {new Date(rows('observations')[0].recorded_at).toLocaleString()}: BP {rows('observations')[0].systolic??'—'}/{rows('observations')[0].diastolic??'—'}, temperature {rows('observations')[0].temperature??'—'} °C</Text>}<Text style={styles.label}>Current medicines</Text>{rows('prescriptions').filter(p=>currentPrescription(p)).slice(0,3).map(p=><Text key={p.id} style={styles.subtitle}>{p.medication} · {p.instructions}</Text>)}{!rows('prescriptions').some(p=>currentPrescription(p))&&<Text style={styles.muted}>None recorded</Text>}<Button onPress={()=>setPatientTab('Current visit')}>Open current visit</Button></Card><CareCoordination patient={patient} context={context} mode="concerns"/>{rows('referrals').filter(r=>r.target_facility_id===f).map(r=><Card key={r.id} title="Referral handover"><Text style={styles.subtitle}>From {r.origin_facility_name||'Referring institution'}</Text><Text style={styles.subtitle}>Referring colleague: {r.referring_staff_name||'Not recorded'}</Text><Text style={styles.subtitle}>Previous clinician: {r.referring_doctor_name||'Not recorded'}</Text><Text style={styles.subtitle}>{r.reason}</Text><Text style={styles.subtitle}>Receiving clinician: {r.receiving_doctor_name||'Not yet assigned'}</Text></Card>)}</>}
 {patientTab==='Care plan'&&<><CareCoordination patient={patient} context={context}/><Button ghost onPress={()=>open('Assign patient follow-up','task_create',taskFields(rows('colleagues')),{patient_id:patient.id,assigned_to:user.id,priority:'routine'})}>Assign patient task</Button></>}
 {patientTab==='Current visit'&&<>
 {nursing&&!activeVisit&&<Button onPress={()=>open('Register arrival','arrive',[['priority','Priority','select',['routine','urgent','emergency']],['notes','Reason for visit','textarea']],{patient_id:patient.id,priority:'routine'})}>Register arrival</Button>}
 {activeVisit&&<Card title="Current visit"><Text style={styles.subtitle}>Responsible clinician: {activeVisit.assigned_doctor_name||'Not yet assigned'}</Text><Button ghost onPress={()=>open('Assign responsible clinician','assign_doctor',[['doctor_id','Clinician at this institution','select',choices(rows('colleagues').filter(m=>['doctor','admin'].includes(m.role)),m=>m.name)]],{id:activeVisit.id,version:activeVisit.version,doctor_id:activeVisit.assigned_doctor_id||''})}>Assign clinician</Button><Badge value={activeVisit.status}/><Text style={styles.subtitle}>{activeVisit.notes}</Text><Button onPress={()=>open('Update visit','visit',[['status','Next stage','select',clinical?['waiting','triage','consultation','awaiting_tests','completed','cancelled']:['waiting','triage','consultation','cancelled']],...(clinical?[['diagnosis','Diagnosis / assessment','textarea'],['follow_up_date','Follow-up date','date']]:[]),['notes','Visit notes','textarea']],{id:activeVisit.id,version:activeVisit.version,status:activeVisit.status,...(clinical?{diagnosis:activeVisit.diagnosis||'',follow_up_date:activeVisit.follow_up_date||''}:{}),notes:activeVisit.notes||''},{description:'Completed visits are locked. Review the notes before completing.'})}>Update visit</Button><Button ghost onPress={()=>open('Record observations','observe',[['temperature','Temperature °C','number'],['systolic','Systolic mmHg','number'],['diastolic','Diastolic mmHg','number'],['pulse','Pulse / min','number'],['weight','Weight kg','number'],['spo2','SpO₂ %','number'],['notes','Observation notes','textarea']],{visit_id:activeVisit.id})}>Record observations</Button>{clinical&&<Button ghost onPress={()=>open('Request laboratory test','lab_order',[['test_type','Test name']],{patient_id:patient.id,visit_id:activeVisit.id})}>Request test</Button>}</Card>}
 {clinical&&<Button onPress={()=>open('Write prescription','prescribe',[['medication','Medicine (generic name and strength)'],['instructions','Dose, route, frequency and duration','textarea'],['quantity','Quantity','number'],['ends_on','Treatment end date','date'],['pharmacy_id','Dispensing institution','select',[{value:'',label:'This institution'},...rows('facilities').filter(x=>x.status==='active'&&x.facility_type!=='laboratory').map(x=>({value:x.id,label:x.name}))]]],{patient_id:patient.id})}>Write prescription</Button>}
 {nursing&&<Button ghost onPress={()=>open('Refer patient','refer',[['target_facility_id','Receiving institution','select',choices(rows('facilities').filter(x=>x.id!==f),x=>x.name)],['reason','Referral reason and summary','textarea'],['consent_recorded','Patient or guardian agrees to share this referral','select',[{value:'',label:'Choose…'},{value:'yes',label:'Consent recorded'}]]],{patient_id:patient.id})}>Refer patient</Button>}
 </>}
 {patientTab==='History'&&<>
 {rows('observations').map(o=><Card key={o.id} title={'Observations · '+new Date(o.recorded_at).toLocaleDateString()}><Text style={styles.subtitle}>Temperature {o.temperature??'—'} · BP {o.systolic??'—'}/{o.diastolic??'—'} · Pulse {o.pulse??'—'} · SpO₂ {o.spo2??'—'}%</Text><Text style={styles.subtitle}>{o.notes}</Text></Card>)}
 {rows('labs').map(labCard)}
 {rows('prescriptions').map(p=><Card key={p.id} title={p.medication}><Badge value={currentPrescription(p)?'active':p.status==='active'?'ended':p.status}/><Text style={styles.subtitle}>{p.instructions}</Text><Text style={styles.muted}>Quantity {p.quantity} · {p.ends_on||'No end date recorded'}</Text></Card>)}
 {rows('visits').map(v=><Card key={v.id} title={new Date(v.date).toLocaleDateString()}><Badge value={v.status}/>{v.assigned_doctor_name&&<Text style={styles.subtitle}>Responsible clinician: {v.assigned_doctor_name}</Text>}<Text style={styles.subtitle}>{v.diagnosis||'No diagnosis recorded'}</Text><Text style={styles.subtitle}>{v.notes}</Text>{v.follow_up_date&&<Text style={styles.subtitle}>Follow-up: {v.follow_up_date}</Text>}</Card>)}
 <NativePatientCard patient={patient} onError={setError}/></>}
 </>:<>
 {!['Today','My care'].includes(tab)&&<Text style={styles.title}>{tab}</Text>}
 {tab==='More'&&<>{tabs.filter(t=>!primary.includes(t)).map(t=><Button key={t} ghost onPress={()=>setTab(t)}>{t}</Button>)}</>}
 {tab==='Tasks'&&<CareTasks rows={rows('tasks')} team={rows('colleagues')} user={user} open={open} onHistoryChange={setTaskHistory} onLaboratory={()=>setTab('Laboratory')}/>}
 {tab==='Care plan'&&(rows('patients')[0]?<><CareCoordination patient={rows('patients')[0]} context={context}/><CareCoordination patient={rows('patients')[0]} context={context} mode="concerns"/></>:<Text style={styles.muted}>Link your patient record from My care to see your care plan.</Text>)}
 {tab==='Today'&&<NativeDashboard role={role} data={data} facility={f} user={user} onAction={dashboardAction} onPatient={openPatient} loading={busy} lastUpdated={lastUpdated} error={error}/> }
 {tab==='Patients'&&<><TextInput accessibilityLabel="Search patients" placeholder="Search name, phone or ID" value={search} onChangeText={setSearch} style={styles.input}/><Button onPress={()=>open('Register patient','register',intakeFields,{})}>Register patient</Button>{rows('patients').map(p=><Card key={p.id} title={p.first_name+' '+p.last_name}><Text selectable style={styles.muted}>{p.id}</Text><Text style={styles.subtitle}>{p.phone||'No phone recorded'}</Text><Button ghost onPress={()=>setPatient(p)}>Open record</Button></Card>)}</>}
 {tab==='Laboratory'&&<>{labtech&&<Button onPress={()=>setUpload(true)}>Add standalone result</Button>}{rows('labs').map(labCard)}</>}
 {tab==='Stock'&&<><Button onPress={()=>open('Receive stock batch','stock',[['medication','Medicine (generic name and strength)'],['batch_number','Batch number'],['expires_on','Expiry date','date'],['quantity','Quantity received','number'],['unit_price','Unit price, FCFA','number']])}>Receive stock</Button>{rows('stock').map(b=><Card key={b.id} title={b.medication}><Text style={styles.subtitle}>{b.batch_number} · {b.quantity} units · {money(b.unit_price)}</Text><Text style={styles.subtitle}>Expires {b.expires_on}</Text>{b.expires_on<=new Date().toISOString().slice(0,10)&&<Badge value="expired"/>}{b.quantity<=5&&<Badge value="low_stock"/>}</Card>)}</>}
 {tab==='Pharmacy'&&rows('prescriptions').filter(p=>(p.pharmacy_id===f||(!p.pharmacy_id&&p.facility_id===f))&&currentPrescription(p)).map(p=><Card key={p.id} title={p.medication}><Text style={styles.subtitle}>{p.patient_id}</Text><Text style={styles.subtitle}>{p.instructions}</Text><Text style={styles.subtitle}>Prescribed quantity: {p.quantity}</Text><Button onPress={()=>open('Record dispensing','dispense',[['batch_id','Matching unexpired batch','select',choices(rows('stock').filter(b=>b.quantity>0&&b.expires_on>new Date().toISOString().slice(0,10)&&b.medication.trim().toLowerCase()===p.medication.trim().toLowerCase()),b=>b.batch_number+' · '+b.quantity+' available')],['quantity','Quantity dispensed now','number']],{prescription_id:p.id})}>Dispense</Button></Card>)}
 {tab==='Appointments'&&<><Button onPress={()=>open('Book appointment','appointment',appointmentFields)}>Book appointment</Button>{rows('appointments').map(a=><Card key={a.id} title={a.patient_id}><Badge value={a.status}/><Text style={styles.subtitle}>{new Date(a.scheduled_at).toLocaleString()} · {a.reason}</Text>{a.status==='requested'&&<Button disabled={mutating} onPress={()=>act('appointment_status',{id:a.id,status:'confirmed'})}>Confirm</Button>}{['requested','confirmed'].includes(a.status)&&<><Button disabled={mutating} ghost onPress={()=>act('appointment_status',{id:a.id,status:'arrived'})}>Arrived — add to queue</Button><Button disabled={mutating} ghost onPress={()=>act('appointment_status',{id:a.id,status:'cancelled'})}>Cancel</Button></>}</Card>)}</>}
 {tab==='Referrals'&&rows('referrals').filter(r=>r.facility_id===f||r.target_facility_id===f).map(r=><Card key={r.id} title={(r.target_facility_id===f?'Incoming':'Outgoing')+' · '+r.patient_id}><Badge value={r.status}/><Text style={styles.subtitle}>From {r.origin_facility_name||'Referring institution'}</Text><Text style={styles.subtitle}>Referring colleague: {r.referring_staff_name||'Not recorded'}</Text><Text style={styles.subtitle}>Previous clinician: {r.referring_doctor_name||'Not recorded'}</Text><Text style={styles.subtitle}>Receiving clinician: {r.receiving_doctor_name||'Not yet assigned'}</Text><Text style={styles.subtitle}>{r.reason}</Text>{r.target_facility_id===f&&r.status==='sent'&&<><Button disabled={mutating} onPress={()=>act('referral_status',{id:r.id,status:'accepted'})}>Accept referral</Button><Button disabled={mutating} ghost onPress={()=>act('referral_status',{id:r.id,status:'declined'})}>Decline</Button></>}{r.target_facility_id===f&&r.status==='accepted'&&<Button ghost onPress={()=>open('Assign receiving clinician','referral_assign',[['doctor_id','Clinician at this institution','select',choices(rows('colleagues').filter(m=>['doctor','admin'].includes(m.role)),m=>m.name)]],{id:r.id,version:r.version,doctor_id:r.receiving_doctor_id||''})}>Assign receiving clinician</Button>}{r.target_facility_id===f&&r.status==='accepted'&&<Button disabled={mutating} onPress={()=>act('referral_status',{id:r.id,status:'completed'})}>Mark completed</Button>}</Card>)}
 {tab==='Billing'&&<><Text style={styles.subtitle}>Record staff-confirmed receipts in FCFA. Mobile-money transactions are not automatically verified.</Text><Button onPress={()=>open('Create invoice','invoice',[['patient_id','Patient Careline ID'],['description','Service or items'],['total','Total, FCFA','number']])}>Create invoice</Button>{rows('invoices').map(i=><Card key={i.id} title={i.description}><Badge value={i.status}/><Text style={styles.subtitle}>{i.patient_id} · {money(i.total)}</Text>{i.status==='open'&&<Button onPress={()=>open('Record received payment','pay',[['amount','Amount received, FCFA','number'],['method','Method','select',[{value:'cash',label:'Cash'},{value:'mtn_momo',label:'MTN Mobile Money'},{value:'orange_money',label:'Orange Money'}]],['reference','Transaction reference (required for mobile money)']],{invoice_id:i.id,method:'cash'})}>Record payment</Button>}</Card>)}</>}
 {tab==='Notice board'&&<><Button onPress={()=>open('Post a notice','notice',[['content','Notice','textarea'],['priority','Priority','select',['normal','urgent']],['target_type','Audience','select',[{value:'all',label:'All staff'},{value:'role',label:'Staff role'},{value:'individual',label:'One colleague'}]],['target_role','Role (for role notices)','select',['nurse','doctor','labtech','pharmacist','admin']],['target_user_id','Colleague (for direct notices)','select',choices(rows('colleagues'),x=>x.name+' · '+x.role)]],{priority:'normal',target_type:'all'})}>Post notice</Button>{rows('notices').map(n=><Card key={n.id} title={n.author_name}><Badge value={n.priority}/><Text style={styles.subtitle}>{n.content}</Text><Text style={styles.muted}>{new Date(n.created_at).toLocaleString()} · {n.target_type==='all'?'All staff':n.target_type==='role'?n.target_role:'Direct notice'}</Text>{(n.author_id===user.id||role==='admin')&&<Button ghost disabled={mutating} onPress={()=>act('delete_notice',{id:n.id})}>Remove notice</Button>}</Card>)}</>}
 {tab==='Institutions'&&<><Button onPress={()=>open('Apply for your institution','apply',[['name','Institution name'],['facility_type','Type','select',['health_centre','clinic','hospital','laboratory','pharmacy']],['registration_number','Registration / licensing reference'],['region','Region'],['location','Address / landmark'],['phone','Contact phone'],['services','Services'],['opening_hours','Opening hours']],{facility_type:'health_centre'})}>Apply for your institution</Button>{rows('facilities').map(x=><Card key={x.id} title={x.name}><Badge value={x.status}/><Text style={styles.subtitle}>{x.facility_type.replaceAll('_',' ')} · {x.region}</Text><Text style={styles.subtitle}>{x.location}</Text><Text style={styles.subtitle}>{x.services}</Text><Text style={styles.muted}>{x.opening_hours}</Text>{x.phone&&<Button ghost onPress={()=>Linking.openURL('tel:'+x.phone)}>Call {x.phone}</Button>}{context.is_operator&&x.status==='pending'&&<Button onPress={()=>Alert.alert('Activate institution','Have you verified its registration and owner?',[{text:'Cancel'},{text:'Approve',onPress:async()=>{try{await rpc('careline_approve_facility',{f:x.id});reload()}catch(e){setError(e.message)}}}])}>Approve verified institution</Button>}</Card>)}</>}
 {tab==='Team'&&<>{rows('links').filter(l=>l.status==='pending').map(l=><Card key={l.id} title="Patient account link request"><Text style={styles.subtitle}>{l.patient_id}</Text><Text style={styles.muted}>Verify this person's identity in person before linking account {l.requested_by}.</Text><Button disabled={mutating} onPress={()=>act('approve_link',{id:l.id})}>Approve verified identity</Button></Card>)}<Text style={styles.subtitle}>Nurses can handle reception duties. Staff access is assigned to a verified email.</Text><Button onPress={()=>open('Invite staff','invite',[['email','Staff email','email'],['role','Responsibility','select',['nurse','doctor','labtech','pharmacist','admin']],['verified','I have confirmed this person works at this institution','select',[{value:'',label:'Confirm employment'},{value:'yes',label:'Yes, verified by me'}]]],{role:'nurse'})}>Add staff member</Button>{rows('invitations').filter(i=>!i.accepted_at&&new Date(i.expires_at)>new Date()).map(i=><Card key={i.id} title={i.email}><Text style={styles.subtitle}>{i.role} - awaiting email verification</Text><Button ghost onPress={async()=>{try{await Share.share({message:'Your institution has invited you to Careline. Open this private setup link in the installed app: careline://staff-activate?code='+i.activation_code})}catch(e){setError(e.message)}}}>Share private setup link</Button><Button ghost disabled={mutating} onPress={()=>act('revoke_invitation',{id:i.id})}>Revoke invitation</Button></Card>)}{rows('members').map(m=>{const p=rows('profiles').find(p=>p.id===m.user_id);return <Card key={m.user_id} title={p?.name||m.user_id}><Text style={styles.subtitle}>{p?.email} · {m.role}</Text><Text style={styles.muted}>Staff badge: {m.badge_id}</Text><Badge value={m.active?'active':'inactive'}/><Button ghost onPress={()=>open('Manage membership','member',[['role','Responsibility','select',['nurse','doctor','labtech','pharmacist','admin']],['active','Active membership','select',[{value:'yes',label:'Active'},{value:'no',label:'Inactive'}]]],{user_id:m.user_id,role:m.role,active:m.active?'yes':'no'})}>Manage access</Button></Card>})}</>}
 {tab==='My care'&&<>{busy&&!rows('patients').length?<Text style={styles.muted}>Loading your care...</Text>:error&&!rows('patients').length?<Button ghost onPress={reload}>Retry loading my care</Button>:rows('patients')[0]?<>{portalSection==='Overview'?<NativeDashboard role="patient" data={data} facility={f} user={user} onAction={dashboardAction} loading={busy} lastUpdated={lastUpdated} error={error}/>:<><Button ghost onPress={()=>setPortalSection('Overview')}>Back to my care</Button><Text style={styles.title}>{portalSection}</Text></>}{portalSection==='Card'&&<NativePatientCard patient={rows('patients')[0]} onError={setError}/>}{portalSection==='Appointments'&&<Button onPress={()=>open('Request appointment','appointment',[['target_f','Institution','select',choices(rows('facilities').filter(x=>x.status==='active'),x=>x.name)],...appointmentFields.slice(1)],{patient_id:rows('patients')[0].id})}>Request appointment</Button>}{portalSection==='Medicines'&&rows('prescriptions').filter(p=>currentPrescription(p)).map(p=><Card key={p.id} title={p.medication}><Text style={styles.subtitle}>{p.instructions}</Text><Text style={styles.muted}>Current prescription · {p.ends_on||'No end date recorded'}</Text></Card>)}{portalSection==='Appointments'&&rows('appointments').map(a=><Card key={a.id} title={new Date(a.scheduled_at).toLocaleString()}><Badge value={a.status}/><Text style={styles.subtitle}>{a.reason}</Text></Card>)}{portalSection==='Payments'&&rows('invoices').map(i=><Card key={i.id} title={i.description}><Badge value={i.status}/><Text style={styles.subtitle}>{money(i.total)}</Text></Card>)}{portalSection==='History'&&rows('labs').map(labCard)}{portalSection==='History'&&rows('visits').map(v=><Card key={v.id} title={new Date(v.date).toLocaleDateString()}>{v.assigned_doctor_name&&<Text style={styles.subtitle}>Responsible clinician: {v.assigned_doctor_name}</Text>}<Text style={styles.subtitle}>{v.diagnosis||'No diagnosis recorded'}</Text><Text style={styles.subtitle}>{v.notes}</Text>{v.prescription&&<Text style={styles.muted}>Historical prescription: {v.prescription}</Text>}{v.follow_up_date&&<Text style={styles.subtitle}>Follow-up: {v.follow_up_date}</Text>}</Card>)}</>:<Card title="Link your existing patient record"><Text style={styles.subtitle}>Your facility must verify your identity before linking an existing record. Staff can also refresh access after their email invitation is accepted.</Text><Button onPress={()=>open('Link patient record','request_link',[['patient_id','Patient ID from your Careline card'],['target_f','Registering facility','select',choices(rows('facilities'),x=>x.name)]])}>Request record linking</Button><Button ghost onPress={refreshContext}>Refresh staff access</Button></Card>}</>}
 {tab==='Account'&&<Card title={context.name||'Your account'}>{context.memberships.map(m=><View key={m.facility_id} style={{gap:6,padding:16,borderRadius:12,backgroundColor:'#e9f0e4'}}><Text style={styles.heading}>{m.name}</Text><Text style={styles.subtitle}>{m.role} - active institution membership</Text><Text selectable style={styles.muted}>{m.badge_id}</Text></View>)}<Text style={styles.subtitle}>{user.email||user.phone}</Text><Button onPress={()=>open('Update account','account',[['name','Display name'],['password','New password (optional)','password']],{name:context.name||''})}>Edit account</Button><Button ghost onPress={refreshContext}>Refresh institution access</Button><Button ghost onPress={async()=>{const {error}=await supabase.auth.signOut();if(error)setError(error.message)}}>Sign out</Button></Card>}
 {Object.values(data).some(v=>Array.isArray(v)&&v.length>=100)&&<Text style={styles.muted}>Showing the latest 100 records. Search by patient ID to find an older patient.</Text>}
 {!busy&&!error&&!['Account','Institutions','My care','Care plan','More','Tasks'].includes(tab)&&Object.entries(data).filter(([k])=>k!=='facilities').every(([,v])=>!v.length)&&<Text style={styles.muted}>No records in this worklist yet.</Text>}
 </>}
 </ScrollView><View style={{flexDirection:'row',borderTopWidth:1,borderTopColor:'#d8dfd9',paddingBottom:Math.max(insets.bottom,8),paddingTop:8,backgroundColor:'#faf8f2'}}>{[...primary,'More'].map(t=><TouchableOpacity key={t} accessibilityRole="button" accessibilityState={{selected:!patient&&(tab===t||(t==='More'&&!primary.includes(tab)))}} onPress={()=>{setPatient(null);setTab(t);setMessage('')}} style={{flex:1,paddingVertical:10,alignItems:'center',backgroundColor:!patient&&tab===t?'#e1ebe4':'transparent'}}><Text style={{color:'#173b2e',fontWeight:'600',fontSize:12}}>{t}</Text></TouchableOpacity>)}</View>{upload&&<NativeResultUpload facility={f} onClose={()=>setUpload(false)} onSaved={()=>{setMessage('Result saved for clinician review.');reload()}}/>}{form&&<FormModal key={form.title+':'+(form.initial?.id||'new')} form={form} onClose={()=>setForm(null)} onSave={save}/>}</View>
}
